import { execFileSync } from "node:child_process";
import { decodeVision } from "../src/server/maniglie/vision-decode";
import { parseVision, BANDE_VISION_2026 } from "../src/server/maniglie/vision-parse";
import { articoliVision } from "../src/server/maniglie/vision-codici";
const pdf = "/tmp/claude-0/-home-user-AGB-Finder/e6bf1587-fae4-5464-8cb5-97e581c01c58/scratchpad/vision2026.pdf";
const raw = execFileSync("pdftotext", ["-layout", pdf, "-"], { maxBuffer: 64e6, encoding: "buffer" });
const { esclusi } = articoliVision(parseVision(decodeVision(raw), BANDE_VISION_2026));
console.log("esclusi totali:", esclusi.length);
const perModello = esclusi.map(e => e.modello);
const conteggio = new Map<string, number>();
for (const m of perModello) conteggio.set(m, (conteggio.get(m) ?? 0) + 1);
console.log("modelli distinti:", conteggio.size);
for (const [m, n] of [...conteggio].sort()) if (n > 1) console.log(`  RIPETUTO ${n}×: ${m}`);
console.log("elenco:", [...conteggio.keys()].sort().join(", "));
